### ISSUE TITLE
WHO Parser can't connect to S3

### ISSUE THREAD

**Issue by SamDepardieu** [wellcometrust/reference-parser#18]
Complete output:
```
/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
import imp
[2018-11-05 05:02:27,205]:INFO - [+] Reading input files for who
Traceback (most recent call last):
File "main.py", line 110, in <module>
run_predict(scraper_file, references_file, model_file, vectorizer_file)
File "main.py", line 21, in run_predict
scraper_file = fm.get_file(scraper_file_name, scraper_file_dir, 'json')
File "/reference_parser/utils/file_manager.py", line 25, in get_file
return self.get_from_s3(file_prefix, file_name, file_type)
File "/reference_parser/utils/file_manager.py", line 35, in get_from_s3
file_content = self.s3.get(file_path)
File "/reference_parser/utils/s3.py", line 38, in get
Key=key
File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 320, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 623, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
```

💡 
- Check data-labs-infra code for IDs/IAM role missing
- Check settings (unlikely, only happens on WHO)

**Comment by SamDepardieu** [comment]
Happening since `2018-10-24`. Was working fine before.

**Comment by SamDepardieu** [comment]
WHO has no content in S3

**Comment by SamDepardieu** [comment]
Running a local quick scrape (25 items)
