### ISSUE TITLE
Database insertion failed on AWS

### ISSUE THREAD

**Issue by SamDepardieu** [wellcometrust/reference-parser#21]
See log from November 12th.
```
Fuzzy matching for 404921 predicted publications ...
Document id ... Cosine_Similarity
0 c66d5fc8b818b513226c6c56de130fe1 ... 0.835035
1 ce7bce81e6cc76bf46576cba7d2e7ee6 ... 1.000000
2 ce7bce81e6cc76bf46576cba7d2e7ee6 ... 1.000000
3 1d90f9b3917923710e90623ddf76495d ... 0.804035
4 5ca40f789771eb6451b19a58b6955763 ... 0.937297
[5 rows x 6 columns]
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
context)
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
cursor.execute(statement, parameters)
psycopg2.IntegrityError: duplicate key value violates unique constraint "document_pkey"
DETAIL: Key (id)=(553) already exists.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "main.py", line 133, in <module>
run_predict(scraper_file, references_file, model_file, vectorizer_file)
File "main.py", line 82, in run_predict
all_match_data,
File "/reference_parser/models.py", line 89, in save_to_database
and Document.title == serial_doc['title']
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2895, in first
ret = list(self[0:1])
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2687, in __getitem__
return list(res)
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2994, in __iter__
self.session._autoflush()
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1444, in _autoflush
util.raise_from_cause(e)
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
raise value
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1434, in _autoflush
self.flush()
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
self._flush(objects)
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
transaction.rollback(_capture_exception=True)
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
compat.reraise(exc_type, exc_value, exc_tb)
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
raise value
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
flush_context.execute()
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
rec.execute(self)
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
uow
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
mapper, table, insert)
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 866, in _emit_insert_statements
execute(statement, params)
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
return meth(self, multiparams, params)
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
compiled_sql, distilled_params
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
context)
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
exc_info
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
raise value.with_traceback(tb)
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
context)
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.IntegrityError) duplicate key value violates unique constraint "document_pkey"
DETAIL: Key (id)=(553) already exists.
[SQL: 'INSERT INTO document (author, issue, journal, volume, pub_year, pagination, title, file_hash, id_organisation, datetime_creation, datetime_update) VALUES (%(author)s, %(issue)s, %(journal)s, %(volume)s, %(pub_year)s, %(pagination)s, %(title)s, %(file_hash)s, %(id_organisation)s, %(datetime_creation)s, %(datetime_update)s) RETURNING document.id'] [parameters: {'author': None, 'issue': None, 'journal': None, 'volume': None, 'pub_year': None, 'pagination': None, 'title': 'maternal-mortality-2015/en/', 'file_hash': '28cf4976bf50710c7477562fa861fa4b', 'id_organisation': 1, 'datetime_creation': '2018-11-13 07:14:29', 'datetime_update': datetime.datetime(2018, 11, 12, 17, 8, 54, 47921)}] (Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by SamDepardieu** [comment]
Launched a full parsing to check that it wasn't just some kind of concurrency issue

**Comment by SamDepardieu** [comment]
Still got the issue with the last version running alone. Investigating further

**Comment by SamDepardieu** [comment]
It seems like two runs of the parser over the same set of documents doesn't output the same result. The file hash are the same, but author, title, journal etc seems to change. Looking further in

**Comment by SamDepardieu** [comment]
Local logs:
```
[2018-11-28 15:52:07,762]:INFO - [+] Reading input files for who_iris
[2018-11-28 15:52:07,762]:INFO - [+] Trying to fetch scraper-results/who/who_iris_light.json from s3
[2018-11-28 15:52:09,145]:INFO - Using scraper-results/who/who_iris_light.json file from S3
[2018-11-28 15:52:09,327]:INFO - [+] Trying to fetch wellcome_publications/uber_api_publications.csv from s3
[2018-11-28 15:52:13,526]:INFO - Using wellcome_publications/uber_api_publications.csv file from S3
[2018-11-28 15:52:14,109]:INFO - [+] Trying to fetch reference_parser_models/RefSorter_classifier.pkl from s3
[2018-11-28 15:52:14,547]:INFO - Using reference_parser_models/RefSorter_classifier.pkl file from S3
[2018-11-28 15:52:14,556]:INFO - [+] Trying to fetch reference_parser_models/RefSorter_vectorizer.pkl from s3
[2018-11-28 15:52:14,832]:INFO - Using reference_parser_models/RefSorter_vectorizer.pkl file from S3
[2018-11-28 15:52:14,848]:INFO - [+] Spliting the references
Processing unstructured references into reference components ...
Reference components found
[2018-11-28 15:52:14,968]:INFO - [+] Predicting the reference components
[2018-11-28 15:52:14,968]:INFO - [+] Predicting the categories of 4378  reference components ...
[2018-11-28 15:52:14,992]:INFO - [+] Using pooled predictor with 4 workers
[2018-11-28 15:52:17,159]:INFO - Predictions complete
[2018-11-28 15:52:17,160]:INFO - [+] Predicting structure of references from 14  documents...
[2018-11-28 15:52:17,175]:INFO - [+] Using pooled predictor with 4 workers
[2018-11-28 15:52:26,930]:INFO - [+] Reference structure predicted
[2018-11-28 15:52:29,020]:INFO - Fuzzy matching for 1635 predicted publications ...
[2018-11-28 15:52:31,767]:INFO -                         Document id         Reference id        ...              WT_Ref_Id Cosine_Similarity
0  82003c449a47fc1ca81f9420a7f56428  7919203673845709549        ...         pub.1046691005          0.884852
1  fd87c0e6e59ebc0ed39f3b0190d7b5bd  1037676870880986938        ...         pub.1016710435          0.876554

[2 rows x 6 columns]
[2018-11-28 15:52:34,199]:INFO - Time taken to predict and match for 4378 is 19.230857849121094
```

AWS logs:
```
[2018-11-28 15:53:36,967]:INFO - [+] Reading input files for who
[2018-11-28 15:53:37,038]:INFO - [+] Trying to fetch scraper-results/who/who_iris_light.json from s3
[2018-11-28 15:53:37,373]:INFO - Using scraper-results/who/who_iris_light.json file from S3
[2018-11-28 15:53:37,552]:INFO - [+] Trying to fetch wellcome_publications/uber_api_publications.csv from s3
[2018-11-28 15:53:38,075]:INFO - Using wellcome_publications/uber_api_publications.csv file from S3
[2018-11-28 15:53:38,661]:INFO - [+] Trying to fetch reference_parser_models/RefSorter_classifier.pkl from s3
[2018-11-28 15:53:38,823]:INFO - Using reference_parser_models/RefSorter_classifier.pkl file from S3
[2018-11-28 15:53:38,825]:INFO - [+] Trying to fetch reference_parser_models/RefSorter_vectorizer.pkl from s3
[2018-11-28 15:53:39,006]:INFO - Using reference_parser_models/RefSorter_vectorizer.pkl file from S3
[2018-11-28 15:53:39,019]:INFO - [+] Spliting the references
[2018-11-28 15:53:39,206]:INFO - [+] Predicting the reference components
[2018-11-28 15:53:39,207]:INFO - [+] Predicting the categories of 4378 reference components ...
Processing unstructured references into reference components ...
Reference components found
[2018-11-28 15:53:39,224]:INFO - [+] Using pooled predictor with 4 workers
[2018-11-28 15:53:42,944]:INFO - Predictions complete
[2018-11-28 15:53:42,945]:INFO - [+] Predicting structure of references from 14 documents...
[2018-11-28 15:53:42,959]:INFO - [+] Using pooled predictor with 4 workers
[2018-11-28 15:53:53,728]:INFO - [+] Reference structure predicted
[2018-11-28 15:53:56,163]:INFO - Fuzzy matching for 1635 predicted publications ...
[2018-11-28 15:53:58,600]:INFO - Document id ... Cosine_Similarity
0 fd87c0e6e59ebc0ed39f3b0190d7b5bd ... 0.876554
1 82003c449a47fc1ca81f9420a7f56428 ... 0.884852
[2 rows x 6 columns]
[2018-11-28 15:54:02,564]:INFO - Time taken to predict and match for 4378 is 23.357622385025024
```

**Comment by SamDepardieu** [comment]
Okay, the missing docs are coming from the way we filter for duplicates. At the moment, the file hash is the only reliable thing we have, as the prediction could predict `None` for about 4 fields on 5. Without this filter, we will have a lot of duplicates (in fact it'll create a duplicate for every entry everytime we run it).

**Comment by SamDepardieu** [comment]
Changed the way we look if the document already exists. Still have an issue with the title. 
I deployed the new version to AWS and it's now running to verify that it solves the insertion issue
